// Go Target Adapter for the ADR 0006 feasibility PoC (non-Rust guest toolchain).
//
// Built with TinyGo targeting wasip2, with bindings generated by wit-bindgen-go
// from the single shared WIT contract. It is semantically equivalent to the
// Rust adapter but, unlike the Rust adapter, does NOT support `descendants`
// propagation: any scope carrying `descendants` is rejected before any target
// mutation. This is the Gate 4 negative case proving a component rejects
// unsupported propagation rather than silently weakening it.

package main

import (
	"go.bytecodealliance.org/cm"

	"permissionsync/adr0006/go-adapter/permissionsync/adr0006/adapter-api"
	"permissionsync/adr0006/go-adapter/permissionsync/adr0006/http"
	"permissionsync/adr0006/go-adapter/permissionsync/adr0006/permissions"
	"permissionsync/adr0006/go-adapter/permissionsync/adr0006/runtime"
)

var allowedRoles = map[string]bool{
	"reader": true, "editor": true, "viewer": true, "technician": true,
}
var allowedGroups = map[string]bool{
	"release-managers": true, "operate": true,
}
var allowedEntitlements = map[string]bool{
	"packet-capture-download": true,
}
var allowedScopeTypes = map[string]bool{"resource-boundary": true, "org": true}
var allowedScopeIDs = map[string]bool{"engineering": true, "operations": true, "north": true}
var allowedConstraintTypes = map[string]bool{"network": true, "interface": true, "allowed": true}
var allowedInterfaces = map[string]bool{"collector-a": true, "collector-b": true}

// outcomeResult is the exact Component-Model result type returned by the
// `reconcile` export: result<outcome, string>.
type outcomeResult = cm.Result[adapterapi.OutcomeShape, adapterapi.Outcome, string]

func reject(msg string) outcomeResult {
	return cm.Err[outcomeResult, adapterapi.OutcomeShape, adapterapi.Outcome, string](msg)
}

func ok(outcome adapterapi.Outcome) outcomeResult {
	return cm.OK[outcomeResult, adapterapi.OutcomeShape, adapterapi.Outcome, string](outcome)
}

func validateAssignment(a permissions.Assignment) error {
	switch a.Kind {
	case permissions.AssignmentKindRole:
		if !allowedRoles[a.ID] {
			return errf("unsupported role '%s'", a.ID)
		}
	case permissions.AssignmentKindGroup:
		if !allowedGroups[a.ID] {
			return errf("unsupported group '%s'", a.ID)
		}
	case permissions.AssignmentKindEntitlement:
		if !allowedEntitlements[a.ID] {
			return errf("unsupported entitlement '%s'", a.ID)
		}
	}
	if s := a.Scope.Some(); s != nil {
		if !allowedScopeTypes[s.ScopeType] {
			return errf("unsupported scope type '%s'", s.ScopeType)
		}
		if !allowedScopeIDs[s.ID] {
			return errf("unsupported scope id '%s'", s.ID)
		}
		// Go adapter does NOT support `descendants` (Gate 4 negative case).
		if s.Propagation == permissions.PropagationDescendants {
			return errf("unsupported propagation 'descendants' (go adapter supports self-only)")
		}
	}
	return nil
}

func validateConstraints(cons cm.List[permissions.Constraint]) error {
	seen := map[string]bool{}
	for _, c := range cons.Slice() {
		if seen[c.ConstraintType] {
			return errf("duplicate constraint type '%s'", c.ConstraintType)
		}
		seen[c.ConstraintType] = true
		if !allowedConstraintTypes[c.ConstraintType] {
			return errf("unsupported constraint type '%s'", c.ConstraintType)
		}
		if c.ConstraintType == "interface" {
			for _, v := range c.Values.Slice() {
				if !allowedInterfaces[v] {
					return errf("unsupported interface value '%s'", v)
				}
			}
		}
	}
	return nil
}

// validateCombination enforces the same per-assignment-kind semantic rule as
// the Rust adapter: `network`/`interface` constraints need a role or group
// assignment, `allowed` constraints need an entitlement assignment. Reject
// before any target mutation (Gate 4).
func validateCombination(doc permissions.Document) error {
	hasRoleGroup := false
	hasEntitlement := false
	for _, a := range doc.Assignments.Slice() {
		if a.Kind == permissions.AssignmentKindRole || a.Kind == permissions.AssignmentKindGroup {
			hasRoleGroup = true
		}
		if a.Kind == permissions.AssignmentKindEntitlement {
			hasEntitlement = true
		}
	}
	for _, c := range doc.Constraints.Slice() {
		switch c.ConstraintType {
		case "network", "interface":
			if !hasRoleGroup {
				return errf("unsupported assignment/constraint combination: '%s' requires a role or group assignment", c.ConstraintType)
			}
		case "allowed":
			if !hasEntitlement {
				return errf("unsupported assignment/constraint combination: 'allowed' requires an entitlement assignment")
			}
		}
	}
	return nil
}

type rejectError struct{ msg string }

func (e *rejectError) Error() string { return e.msg }

func errf(format string, args ...string) error {
	out := format
	for _, a := range args {
		idx := indexOf(out, "%s")
		if idx < 0 {
			break
		}
		out = out[:idx] + a + out[idx+2:]
	}
	return &rejectError{msg: out}
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

func kindStr(k permissions.AssignmentKind) string {
	switch k {
	case permissions.AssignmentKindRole:
		return "role"
	case permissions.AssignmentKindGroup:
		return "group"
	default:
		return "entitlement"
	}
}

func jsonAssignments(doc permissions.Document) string {
	out := "["
	first := true
	for _, a := range doc.Assignments.Slice() {
		if !first {
			out += ","
		}
		first = false
		out += `"` + kindStr(a.Kind) + `:` + a.ID + `"`
	}
	return out + "]"
}

func jsonConstraints(doc permissions.Document) string {
	out := "{"
	first := true
	for _, c := range doc.Constraints.Slice() {
		if !first {
			out += ","
		}
		first = false
		out += `"` + c.ConstraintType + `":[`
		vi := 0
		for _, v := range c.Values.Slice() {
			if vi > 0 {
				out += ","
			}
			out += `"` + v + `"`
			vi++
		}
		out += "]"
	}
	return out + "}"
}

func init() {
	adapterapi.Exports.Reconcile = reconcile
}

func reconcile(doc permissions.Document) cm.Result[adapterapi.OutcomeShape, adapterapi.Outcome, string] {
	if doc.Version != 1 {
		return reject("unsupported model version")
	}
	for _, a := range doc.Assignments.Slice() {
		if err := validateAssignment(a); err != nil {
			return reject(err.Error())
		}
	}
	if err := validateConstraints(doc.Constraints); err != nil {
		return reject(err.Error())
	}
	if err := validateCombination(doc); err != nil {
		return reject(err.Error())
	}

	var effects []adapterapi.TargetEffect
	for _, a := range doc.Assignments.Slice() {
		effects = append(effects, adapterapi.TargetEffect{
			AssignmentID: kindStr(a.Kind) + ":" + a.ID,
			Action:       "grant",
		})
	}

	ctx := runtime.GetContext()
	var contextKeys []string
	for _, i := range ctx.Config.Slice() {
		contextKeys = append(contextKeys, i.Key)
	}
	for _, i := range ctx.Secrets.Slice() {
		contextKeys = append(contextKeys, i.Key)
	}

	endpoint, client, token := "", "", ""
	for _, i := range ctx.Config.Slice() {
		if i.Key == "endpoint" {
			endpoint = i.Value
		}
		if i.Key == "client" {
			client = i.Value
		}
	}
	for _, i := range ctx.Secrets.Slice() {
		if i.Key == "token" {
			token = i.Value
		}
	}
	if endpoint == "" {
		return reject("missing endpoint")
	}
	if client == "" {
		return reject("missing client")
	}
	if token == "" {
		return reject("missing token secret")
	}

	body := `{"assignments":` + jsonAssignments(doc) + `,"constraints":` + jsonConstraints(doc) + `}`
	url := endpoint + "/state?client=" + client
	headers := cm.ToList([]http.Header{{
		Name:  "authorization",
		Value: "Bearer " + token,
	}})
	payload := cm.Some[cm.List[uint8]](cm.ToList([]uint8(body)))

	resp := http.Call("POST", url, headers, payload)
	if resp.IsErr() {
		return reject("http call failed")
	}
	if resp.OK().Status != 200 {
		return reject("target rejected reconcile")
	}

	return ok(adapterapi.Outcome{
		Received:    doc,
		Effects:     cm.ToList(effects),
		Diagnostics: cm.ToList([]string{"go adapter reconciled " + strconv(doc.Assignments.Len()) + " assignments"}),
		ContextKeys: cm.ToList(contextKeys),
	})
}

func strconv(n uintptr) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}

func main() {}
