name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@1e95e14ebea7b312e585f1475a1075a937c8da21 # main
    secrets: inherit
