name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@f8f55a907deb8cdbf504cbf0305d39e3984fb1ca # main
    secrets: inherit
