name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@1e95e14ebea7b312e585f1475a1075a937c8da21 # main
    secrets: inherit
